### ISSUE TITLE
Mongo DB considering RBAC script

### ISSUE THREAD

**Issue by sebiklamar** [isejalabs/homelab#116]
URL: https://github.com/linuxserver/docker-unifi-network-application#setting-up-your-external-database

create your user using an `init-mongo.sh` file with the following contents (do not modify; copy/paste as is):

```sh
#!/bin/bash

if which mongosh > /dev/null 2>&1; then
  mongo_init_bin='mongosh'
else
  mongo_init_bin='mongo'
fi
"${mongo_init_bin}" <<EOF
use ${MONGO_AUTHSOURCE}
db.auth("${MONGO_INITDB_ROOT_USERNAME}", "${MONGO_INITDB_ROOT_PASSWORD}")
db.createUser({
  user: "${MONGO_USER}",
  pwd: "${MONGO_PASS}",
  roles: [
    { db: "${MONGO_DBNAME}", role: "dbOwner" },
    { db: "${MONGO_DBNAME}_stat", role: "dbOwner" }
  ]
})
EOF
```

**Comment by sebiklamar** [comment]
recommended script creates `unifi` user in `admin` database:

```
test> use admin
switched to db admin
admin> show users
[
  {
    _id: 'admin.rootuser',
    userId: UUID('8705ac9e-7b1f-4e58-86e3-2f1167ba7a2b'),
    user: 'rootuser',
    db: 'admin',
    roles: [ { role: 'root', db: 'admin' } ],
    mechanisms: [ 'SCRAM-SHA-1', 'SCRAM-SHA-256' ]
  },
  {
    _id: 'admin.unifiuser',
    userId: UUID('8bcf3f49-146c-42f9-a565-c9f6ce953429'),
    user: 'unifiuser',
    db: 'admin',
    roles: [
      { role: 'dbOwner', db: 'unifidb_stat' },
      { role: 'dbOwner', db: 'unifidb' }
    ],
    mechanisms: [ 'SCRAM-SHA-1', 'SCRAM-SHA-256' ]
  }
]
test> use unifi
switched to db unifi
unifi> show users
[]
```

FYI: unifi DB not shown until data being created

**Comment by sebiklamar** [comment]
see also linuxserver/docker-unifi-network-application#102

**Comment by sebiklamar** [comment]
Hmm, according to [linuxserver/docker-unifi-network-application#114](https://github.com/linuxserver/docker-unifi-network-application/issues/114) using `MONGO_AUTHSOURCE` set to `admin` is working in the wild.

Indeed, [linuxserver documentation](https://github.com/linuxserver/docker-unifi-network-application?tab=readme-ov-file#docker-compose-recommended-click-here-for-more-info) using `MONGO_AUTHSOURCE` (with `admin` set) also for `unifi-network-application` container, i.e. not only for `mongo` container.  That's the trick!

```yaml
---
services:
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=unifi
      - MONGO_PASS=
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
      - MONGO_TLS= #optional
    volumes:
      - /path/to/unifi-network-application/data:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
```

According to [mongo documentation](https://www.mongodb.com/docs/manual/reference/connection-string/#mongodb-urioption-urioption.authSource) `authSource` defaults to `admin` DB if unspecified -- **which unifi container does not use, though.**
