### ISSUE TITLE
Implement Unifi ports

### ISSUE THREAD

**Issue by sebiklamar** [isejalabs/homelab#124]

**Comment by sebiklamar** [comment]
unifi `deployment.yaml` containing ports definition in `spec.containers.ports` stanza and in `spec.ports` stanza, normally.  The latter currently being commented out and still working as per kubernetes service `svc-frontend.yaml`:

```yaml
# deployment-frontend.yaml
spec:
  template:
    spec:
      containers:
        - name: unifi-network-application
          image: lscr.io/linuxserver/unifi-network-application:8.6.9-ls70
          ports:
            - name: web-admin
              containerPort: 8443
              protocol: TCP
            - name: device-comm
              containerPort: 8080
              protocol: TCP
            - name: stun
              containerPort: 3478
              protocol: UDP
            - name: secure-redirect
              containerPort: 8843
              protocol: TCP
            - name: http-redirect
              containerPort: 8880
              protocol: TCP
            - name: speedtest
              containerPort: 6789
              protocol: TCP
            - name: unifi-disc
              containerPort: 10001
              protocol: UDP
            - name: unifi-disc-l2
              containerPort: 1900
              protocol: UDP
#    volumes:
#      - /srv/docker-compose/hosts/unifi/data:/config
#    ports:
#      - 8443:8443
#      - 3478:3478/udp
#      - 10001:10001/udp
#      - 8080:8080
#      - 1900:1900/udp #optional
#      - 8843:8843 #optional
#      - 8880:8880 #optional
#      - 6789:6789 #optional
#      - 5514:5514/udp #optional
```
