### ISSUE TITLE
DRY Gateway with domain transformation

### ISSUE THREAD

**Issue by sebiklamar** [isejalabs/homelab#138]

**Comment by sebiklamar** [comment]
Kustomize's transformers do not work with `Gateway` and `Certificate` because transformer code cannot cope with `*.FQDN` naming and with short domain (`example.com` instead of `foo.example.com`with 1 domain component instead of 2 in addition to TLD).  For the `*.FQDN` one could change the indices.  For the latter (short FQDN) maybe do an additional split iteration.
Needless to say: no domain prefix transformation.

Source... 

```yaml
# base/gw-external.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external
  namespace: gateway
spec:
  listeners:
    - hostname: "*.example.com"
...
    - hostname: example.com
...
```

... becomes in the overlay:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: dev-external
  namespace: gateway
spec:
  listeners:
  - hostname: '*.dev.iseja.net'
...   
  - hostname: example.dev.iseja.net
```
